# Generated by Django 3.0.6 on 2020-10-15 13:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_auto_20201015_2138'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment1',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Post1',
            new_name='Post',
        ),
    ]
